REPLICATE_API_TOKEN="r8_ZvJsXtQhzLSwLt3yUZS8OjmUQ55sqSX2mngHz"
modelrp="a16z-infra/llama13b-v2-chat:df7690f1994d94e96ad9d568eac121aecf50684a0b0963b25a41cc40061269e5"
modelhf="sentence-transformers/all-MiniLM-L6-v2"
username="airlast"
password="hvac"
