REPLICATE_API_TOKEN="r8_ZvJsXtQhzLSwLt3yUZS8OjmUQ55sqSX2mngHz"
modelrp="meta/llama-2-13b-chat:f4e2de70d66816a838a89eeeb621910adffb0dd0baba3976c96980970978018d"
modelhf="sentence-transformers/all-MiniLM-L6-v2"
username="airlast"
password="hvac"
